### ISSUE TITLE
apiary.apib hard to read

### ISSUE THREAD

**Issue by shannona** [bitmark-inc/bitmark-core-doc#1]
apiary.apib does not read cleanly in the online Github interface because it does not an MD suffix. Renaming it to something like apiary-apib.md would solve this problem.

**Comment by jamieabc** [comment]
Hello shannona,

Sorry for the late reply, there's an online version which is more readable, please visit the page [here](https://bitmarkcoreapi.docs.apiary.io/#introduction/overview).

**Comment by araujobsd** [comment]
We are reformatting the documentation and we are building a team to focus and improve it. So, this PR doesn't applies any more.

Thanks @shannona
